url: https://malibudreamhouse.github.io
baseurl: 

# Site settings
title: Malibu Dream House
email: alex.scott.thomsen@gmail.com
description: "We're happy to have you at the Malibu Dream house, Here's everything you need to know"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 46CDF5
  secondary: B6E471
  secondary-dark: 333

# Build settings
markdown: kramdown
permalink: pretty
